### ISSUE TITLE
[NFR] Separate plugin from service

### ISSUE THREAD

**Issue by menta2k** [scakemyer/quasar#16]
Hello this is a new feature request. The idea is to separate kodi plugin from quasar service.

The idea comes with the in-comparability issue with android 5+ (PIE).
so basically ether quasar ether pulsar cant run on android device with  android 5+ so i made an workaround for me . I have a linux based HTPC where i run a quasar service and TV  Sony Bravia with kodi and quasar plugin. Only with few lines of modification in both application they can talk each other.

Probably have many people with my case so if you like i can submit a diff to add such a functionality.

**Comment by scakemyer** [comment]
Quasar was reported to run fine on Android 5+, but this still sounds like an interesting option. Send a PR and I'll sure look into it.

**Comment by Znuff** [comment]
This is over a year old, but I would also like to see the changes required for this.

My reason is that ever since the migration to a new libtorrent version (from almost a year ago), my android boxes can't handle the streaming anymore, unless I allow it to download the file/movie/show I want to watch in full, then I can start watching it.
